name: lol_champs
description: Ejemplo de diseño y animaciones.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.2
  font_awesome_flutter: ^8.10.0
  cached_network_image: ^2.3.3

flutter:
  uses-material-design: true

  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
