/// Flutter icons LolIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  LolIcons
///      fonts:
///       - asset: fonts/LolIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class LolIcons {
  LolIcons._();

  static const _kFontFam = 'LolIcons';
  static const _kFontPkg = null;

  static const IconData champion =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData assassin_role =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fighter_role =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mage_role =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData marksman_role =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData support_role =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tank_role =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
